name: Auto Build and Upload Release

on:
  release:
    types:
      - published # 只有你在网页端发布 Release 才会触发

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 给 gh 命令行赋予上传附件的权限

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 提取动态版本号
        run: |
          # 假设 Tag 是 v2.6.4，将其削掉 v 变成 2.6.4 并存入环境变量
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: 运行 Makefile 自动打包
        run: |
          # 调用 Makefile，并将刚刚提取的版本号传给它
          make all VERSION=${{ env.VERSION }}

      - name: 原地挂载附件到 Release
        shell: bash
        run: |
          gh release upload ${{ env.TAG }} easytier.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}