name: Auto Build and Upload Release

on:
  release:
    types:
      - published # 只有在网页端发布 Release 才会触发

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 赋予上传附件的权限

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 提取动态版本号
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: 构建 HND 平台安装包
        run: |
          # 传入 PLATFORM=hnd
          make all VERSION=${{ env.VERSION }} PLATFORM=hnd

      - name: 构建 QCA 平台安装包
        run: |
          # 传入 PLATFORM=qca
          make all VERSION=${{ env.VERSION }} PLATFORM=qca

      - name: 原地挂载附件到 Release
        shell: bash
        run: |
          # 将当前目录下生成的所有 .tar.gz 文件（easytier_hnd.tar.gz 和 easytier_qca.tar.gz）都上传到 Release 中
          gh release upload ${{ env.TAG }} *.tar.gz
        env:
          GH_TOKEN: ${{ github.token }}